// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";
import {EntryPoint} from "account-abstraction/core/EntryPoint.sol";
import {IEntryPoint} from "account-abstraction/interfaces/IEntryPoint.sol";
import {IntentRegistry} from "../src/IntentRegistry.sol";
import {IntentAccountFactory} from "../src/IntentAccountFactory.sol";
import {AgentRegistry} from "../src/AgentRegistry.sol";

/// @notice Deploys the full AgentIntent stack to ZK Stack L2 (chain 271).
///
/// Usage (with foundry-zksync installed):
///   PRIVATE_KEY=0x... forge script script/DeployZK.s.sol \
///     --rpc-url http://127.0.0.1:3050 \
///     --broadcast \
///     --zksync \
///     --zk-gas-per-pubdata 800 \
///     --slow \
///     -vvv
///
/// Outputs a .env.zk file with deployed addresses for the relayer.
contract DeployZK is Script {
    function run() external {
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerKey);
        // Optional: trust a bundler at deploy time (same pattern as Deploy.s.sol)
        address bundler = vm.envOr("BUNDLER_ADDRESS", address(0));

        vm.startBroadcast(deployerKey);

        // 1. Deploy ERC-4337 EntryPoint (not pre-deployed on ZK Stack L2)
        EntryPoint entryPoint = new EntryPoint();
        console.log("EntryPoint deployed at          :", address(entryPoint));

        // 2. Deploy IntentRegistry and optionally whitelist the bundler
        IntentRegistry registry = new IntentRegistry();
        console.log("IntentRegistry deployed at      :", address(registry));

        if (bundler != address(0)) {
            registry.setBundler(bundler, true);
            console.log("Trusted bundler set             :", bundler);
        }

        // 3. Deploy IntentAccountFactory
        IntentAccountFactory factory = new IntentAccountFactory(IEntryPoint(address(entryPoint)));
        console.log("IntentAccountFactory deployed at:", address(factory));

        // 4. Deploy AgentRegistry
        AgentRegistry agentRegistry = new AgentRegistry();
        console.log("AgentRegistry deployed at       :", address(agentRegistry));

        vm.stopBroadcast();

        // Write addresses to .env.zk for the relayer and run_demo_zk.sh
        string memory out = string.concat(
            "# Auto-generated by DeployZK.s.sol — ZK Stack L2 (chain 271)\n",
            "ZK_ENTRY_POINT=",       vm.toString(address(entryPoint)),    "\n",
            "ZK_REGISTRY=",          vm.toString(address(registry)),      "\n",
            "ZK_FACTORY=",           vm.toString(address(factory)),        "\n",
            "ZK_AGENT_REGISTRY=",    vm.toString(address(agentRegistry)), "\n"
        );
        vm.writeFile("script/.env.zk", out);
        console.log("\nAddresses written to contracts/script/.env.zk");
        console.log("Next: create an IntentAccount via the factory, then start the relayer.");
    }
}
